# Generated by Django 3.2.20 on 2023-10-21 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_auto_20231021_1245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discussion',
            old_name='threads',
            new_name='thread',
        ),
        migrations.AlterField(
            model_name='discussion',
            name='comments',
            field=models.TextField(max_length=100000),
        ),
    ]
