# Generated by Django 3.2.20 on 2023-10-21 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_alter_discussion_writers'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='images',
            field=models.ImageField(default=None, upload_to='static/'),
        ),
    ]
