# Generated by Django 3.2.20 on 2023-10-21 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0010_alter_discussion_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='postuser',
            name='groupMembers',
            field=models.IntegerField(default=1),
        ),
    ]
