# Generated by Django 3.2.20 on 2023-10-21 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0011_postuser_groupmembers'),
    ]

    operations = [
        migrations.AddField(
            model_name='postuser',
            name='timeCreated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
