# Generated by Django 3.2.20 on 2023-10-22 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0012_postuser_timecreated'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogin',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='static/'),
        ),
        migrations.AlterField(
            model_name='userlogin',
            name='gender',
            field=models.CharField(default='', max_length=10),
        ),
    ]
