# Generated by Django 3.2.20 on 2023-10-22 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0013_auto_20231022_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogin',
            name='profile',
            field=models.ImageField(default='media/static/download.jpeg', null=True, upload_to='static/'),
        ),
    ]
