# Generated by Django 3.2.20 on 2023-10-22 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0014_alter_userlogin_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='writers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.userlogin'),
        ),
        migrations.AlterField(
            model_name='userlogin',
            name='profile',
            field=models.ImageField(default='static/download.jpeg', null=True, upload_to='static/'),
        ),
    ]
