# Generated by Django 3.2.20 on 2023-10-25 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0016_alter_discussion_writers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlogin',
            name='profile',
        ),
    ]
