# Generated by Django 3.2.20 on 2023-10-25 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0017_remove_userlogin_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogin',
            name='bio',
            field=models.TextField(default='Create your Community', max_length=1000),
        ),
        migrations.AddField(
            model_name='userlogin',
            name='profile',
            field=models.ImageField(default='static/download.jpeg', null=True, upload_to='static/'),
        ),
    ]
